### ISSUE TITLE
Look into eslint-rule-composer

### ISSUE THREAD

**Issue by hzoo** [babel/eslint-plugin-babel#135]
by @not-an-aardvark, https://github.com/not-an-aardvark/eslint-rule-composer

This should make it much easier to implement these rules, so we should figure out how to refactor the existing ones and also make a guide on how to implement. Might be useful for when a syntax gets to Stage 3/4 so that the implementation here can be used as reference for ESLint later

This repo has been pretty inactive for a while 😄

**Comment by VictorHom** [comment]
Hey! I saw this while perusing and wanted to write down some notes I had trying to apply eslint-rule-composer to semi rule(which is awesome thanks @not-an-aardvark )

2 issues that I ran into:
1. `ruleComposer.joinReports` method isn't the method I want but in my branch, I want to overwrite the return object's VariableDeclaration: checkForSemicolonForVariableDeclaration. In this semi rule of eslint-plugin-babel, the function checkForSemicolonForVariableDeclaration 's regex is updated to include `Await` (compared with the existing version in the eslint repo). If I update `ruleComposer.joinReports` to have its own `VariableDeclaration: checkForSemicolonForVariableDeclaration`, we end up reporting two errors when I run tests. Is there a way to overwrite the method? Or is there an alternative approach?

2. For the case of semi, I essentially just used the same template of the existing semi rule and by wrapping it in ruleComposer.joinReports, I was able to remove the overlapping checks from the eslint semi methods (minus the issue that I have in above). This also means that I didn't actually remove that much code

my [branch](https://github.com/VictorHom/eslint-plugin-babel/commit/dcdf96fc876c5adf0d36020d86d01ce8f81bc992)
sorry about the formatting. VSCode plugin prettier auto format on save

**Comment by not-an-aardvark** [comment]
> `ruleComposer.joinReports` method isn't the method I want but in my branch, I want to overwrite the return object's `VariableDeclaration: checkForSemicolonForVariableDeclaration`. In this semi rule of eslint-plugin-babel, the function checkForSemicolonForVariableDeclaration 's regex is updated to include `Await` (compared with the existing version in the eslint repo). If I update `ruleComposer.joinReports` to have its own `VariableDeclaration: checkForSemicolonForVariableDeclaration`, we end up reporting two errors when I run tests. Is there a way to overwrite the method? Or is there an alternative approach?

By design, it's not possible to override a single listener from a rule in `eslint-rule-composer`. This is because the set of listeners that a rule uses is an implementation detail of the rule. If a listener was overridden with `eslint-rule-composer`, the resulting rule could end up breaking later on if the original rule is refactored to use different listeners. One of the goals of `eslint-rule-composer` is that composed rules are fairly stable, so they usually shouldn't break when a base rule is refactored.

As an alternative, you could use `filterReports` on the original rule to get a new version of the rule where all the problems that would have been reported from the `VariableDeclarator` listener are filtered out. Then you could combine the filtered rule with a rule that only has your new listener, by using `joinReports`.

> For the case of semi, I essentially just used the same template of the existing semi rule and by wrapping it in ruleComposer.joinReports, I was able to remove the overlapping checks from the eslint semi methods (minus the issue that I have in above). This also means that I didn't actually remove that much code

Great! It's true that if you're adding additional cases for a rule to report, your detection logic for those cases will often have some things in common with the original rule implementation. If you're starting from the code of the original `semi` rule, it might be possible to remove some complexity from the implementation if there are special cases that don't apply to the type of code that you're trying to report.
