### ISSUE TITLE
What to do about keeping up to date with an existing eslint rule?

### ISSUE THREAD

**Issue by hzoo** [babel/eslint-plugin-babel#69]
Results in https://github.com/babel/eslint-plugin-babel/issues/63

**Comment by SimenB** [comment]
I don't know if this is the correct issue, but would it be possible to update the readme if (and when) certain rules are not needed, because eslint supports the syntax out of the box?

Maybe by stating what version of eslint and what options are needed.

Things such as async functions and object spread is supported by the default parser, no need for babel for them

**Comment by pizzafroide** [comment]
It would also be great to have a shareable config shipped with this plugin. So we just have to do something like this:
```json
{
  "plugins": [
    "babel"
  ],
  "extends": [
    "plugin:babel/recommended"
  ]
}
```

**Comment by existentialism** [comment]
Closing as we're now using `eslint-plugin-composer` and updated deprecation list in the README with versions.
