### ISSUE TITLE
Is there a reason for maintaining a lonely babel/flow-object-type rule?

### ISSUE THREAD

**Issue by gajus** [babel/eslint-plugin-babel#93]
I'd be happy to migrate it to https://github.com/gajus/eslint-plugin-flowtype.

**Comment by jquense** [comment]
sounds good to me :+1:

**Comment by taion** [comment]
`babel/flow-object-type` is not the only Flow-specific rule here, incidentally.

The following rules:
- `babel/array-bracket-spacing`
- `babel/arrow-parens`

Only make a difference now when using Flow. (The latter because ESLint now supports `async`/`await` natively)

I think it would make more sense to migrate those rules to eslint-plugin-flowtype as well.

**Comment by danharper** [comment]
I'm going to merge `babel/flow-object-type` into `eslint-plugin-flowtype` as `flowtype/object-property-delimiter`.

**Comment by hzoo** [comment]
👍 deprecating everything
